name: cicd

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
    steps:

    name: cicd

on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code Clone from GitHub"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Docker compose deploy the app"
